name: Test Action

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Clone repo
        run: git clone https://salsa.debian.org/ruby-team/lolcat.git -b debian/100.0.1-2
      - name: Test run
        uses: ./
        with:
          source_directory: lolcat
          artifacts_directory: output
      - name: Check files
        run: |
          ls -lh output
          ls -lh output/lolcat_*.*